### ISSUE TITLE
Only wrap lines if there's any tag

### ISSUE THREAD

**Issue by carlosala** [homer0/prettier-plugin-jsdoc#11]
I'm experiencing the following:

```ts
/** This is a JSDoc comment line that exceeds for several characters the printWidth (80).
*/
const foo = () => "bar"
```

If I format, nothing happens.
Nevertheless, if I add `@returns bar` then it wraps all the lines:

```ts
/** This is a JSDoc comment line that exceeds for several characters the printWidth (80).
* @returns bar
*/
const foo = () => "bar"
```
==> format
```ts
/**
 * This is a JSDoc comment line that exceeds for several characters the
 * printWidth (80).
 *
 * @returns Bar.
 */
const foo = () => "bar"
```

Shouldn't it wrap even if tags appear in the comment?

Thanks!

**Comment by homer0** [comment]
Hi @carlosala

That's how it's supposed to work. You can enable [this setting](https://github.com/homer0/prettier-plugin-jsdoc?tab=readme-ov-file#parse-comments-without-tags) to format comments without tags.

Regards
