### ISSUE TITLE
Support node 21 / 22

### ISSUE THREAD

**Issue by campersau** [homer0/prettier-plugin-jsdoc#15]
Currently it only supports `>=18.17 <21` which produces warnings running `npm install` / `npm ci`

https://github.com/homer0/prettier-plugin-jsdoc/blob/e29e3be8166c8d91f907077ee4b73c6e53a22e86/package.json#L38-L41

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@homer0/prettier-plugin-jsdoc@9.0.2',
npm warn EBADENGINE   required: { node: '>=18.17 <21' },
npm warn EBADENGINE   current: { node: 'v22.9.0', npm: '10.[8](https://github.com/campersau/ungit/actions/runs/11157444629/job/31011736263#step:15:9).3' }
npm warn EBADENGINE }
```

**Comment by homer0** [comment]
@campersau sorry, I just saw this and totally missed the promotion of node 22; hopefully we can get #17 merged soon.
