### ISSUE TITLE
Inline comments without tags are not very readable

### ISSUE THREAD

**Issue by mech-tools** [homer0/prettier-plugin-jsdoc#16]
Hi,

When both `jsdocUseInlineCommentForASingleTagBlock`  and `jsdocExperimentalFormatCommentsWithoutTags` are true
Comments without tags are collapsed to a single line if able.

That's ok and more readable for quick type def like `/** @type {string} */`

But for a simple description, we get something like this:
![image](https://github.com/user-attachments/assets/c41b8597-ea7d-4988-b7e2-4fe19228d3bd)

This feels (to me) much more readable:
![image](https://github.com/user-attachments/assets/b7ae6c9f-274e-480f-9e08-309146047f85)

Another example with class:
![image](https://github.com/user-attachments/assets/5a8f49d1-6b46-4b75-9922-fd909fc8ed7d)
![image](https://github.com/user-attachments/assets/93417523-ab6f-4774-af77-27cd675da34c)

Do you think this is smt that can be changed or added as a setting?

**Comment by homer0** [comment]
Hey @mech-tools 👋 

I'll try and take a look today and see if there's an easy fix, but I won't promise you anything, the `jsdocExperimentalFormatCommentsWithoutTags` is not something I plan to get out of experimental; it was a request that was easy enough to add, but not a use case I plan to support nor expand on it.

**Comment by mech-tools** [comment]
Hi @homer0 

Thanks!
Here is my workaround for the time being:

```javascript
import { get, override } from "@homer0/prettier-plugin-jsdoc/src/fns/app.js";
import { loadFns } from "@homer0/prettier-plugin-jsdoc/src/loader.js";
import { getPlugin } from "@homer0/prettier-plugin-jsdoc/src/fns/getPlugin.js";
import { getRenderer } from "@homer0/prettier-plugin-jsdoc/src/fns/getParsers.js";
import { render } from "@homer0/prettier-plugin-jsdoc/src/fns/render.js";

loadFns();

const customGetRenderer = (options) => {
  const renderer = get(render)(options);
  return (column, block) => {
    const padding = " ".repeat(column + 1);
    const prefix = `${padding}* `;
    const lines = renderer(column, block);

    if (
      lines.length === 1 &&
      block.tags.length > 0 && //<------ Added this line
      options.jsdocUseInlineCommentForASingleTagBlock
    ) {
      return `* ${lines[0]} `;
    }

    const useLines = lines.map((line) => `${prefix}${line}`).join("\n");

    return `*\n${useLines}\n${padding}`;
  };
};

override(getRenderer, customGetRenderer);

export default get(getPlugin)();

```

**Comment by homer0** [comment]
hi @mech-tools 

You have no idea how happy it made me to see someone actually used the whole setup to extend the plugin xD!!

So, given that you took your time to learn the api, I added something I hope will fit your use case: [`jsdocExperimentalIgnoreInlineForCommentsWithoutTags`](https://github.com/homer0/prettier-plugin-jsdoc?tab=readme-ov-file#ignore-inline-blocks-for-comments-without-tags).

🤘

**Comment by mech-tools** [comment]
Thanks @homer0. Although, now I have no reason anymore to use the plugin setup ^^
