### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by toridoriv** [homer0/prettier-plugin-jsdoc#8]
@homer0, I'm dropping by to express my immense gratitude for creating this plugin! It's become an indispensable tool for keeping my JSDoc comments clean and consistent.

I'm currently using it with JavaScript and TypeScript and it works wonders. And the ability to create extend the plugin for specific formatting needs is chef's kiss! 🤌 

I can't thank you enough for your hard work and dedication to this project.

![](https://media2.giphy.com/media/xTiN0DurjnZhfWkEuY/giphy.gif)

**Comment by homer0** [comment]
@toridoriv thank you so much :D!! I'm really happy to hear it's helpful for you!
